services:
  valkey:
    image: valkey/valkey:8.0.3-alpine3.21
    container_name: onward-valkey
    restart: unless-stopped
    command: valkey-server --requirepass secret
    ports:
      - 6379:6379
    volumes:
      - valkey:/data

  postgres:
    image: postgres:17.5-alpine3.21
    container_name: onward-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: onward-dev
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1
    container_name: onward-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioaccesskey
      MINIO_ROOT_PASSWORD: miniosecretkey
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    command: server /data --console-address :9001

  weaviate:
    image: semitechnologies/weaviate:1.32.4
    container_name: onward-weaviate
    restart: unless-stopped
    environment:
      ENABLE_MODULES: 'text2vec-openai'
      ASYNC_INDEXING: true
      AUTHENTICATION_APIKEY_ENABLED: true
      AUTHENTICATION_APIKEY_USERS: dummy
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: secret
    command: weaviate --host 0.0.0.0 --port 50050 --scheme http
    ports:
      - 50050:50050
      - 50051:50051
    volumes:
      - weaviate:/data

  learner:
    image: onward/learner:latest
    container_name: onward-learner
    build:
      context: .
      dockerfile: apps/learner/Dockerfile
    ports:
      - 3000:3000

  creator:
    image: onward/creator:latest
    container_name: onward-creator
    build:
      context: .
      dockerfile: apps/creator/Dockerfile
    ports:
      - 3000:3000

volumes:
  valkey:
  postgres:
  minio:
  weaviate:
