services:
  valkey:
    image: valkey/valkey:8.0.3-alpine3.21
    container_name: onward-valkey
    restart: unless-stopped
    command: valkey-server --requirepass secret
    ports:
      - 6379:6379
    volumes:
      - valkey:/data

  postgres:
    image: postgres:17.5-alpine3.21
    container_name: onward-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: onward-dev
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  learner:
    image: onward/learner:latest
    container_name: onward-learner
    build:
      context: .
      dockerfile: apps/learner/Dockerfile
    ports:
      - 3000:3000

volumes:
  valkey:
  postgres:
