onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - protobufjs
  - sharp

patchedDependencies:
  vite-imagetools: patches/vite-imagetools.patch
